# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/

image: cypress/base

stages:
    - build
    - test

build:
    stage: build
    before_script:
        - echo -n "Installing required dependencies..."
        - npm install
    script:
        - npm run build

test:
    stage: test
    before_script:
        - echo -n "Installing required dependencies..."
        - npm install
        - npm run build
    script:
        - npm run e2e:headless
    artifacts:
        when: always
        paths:
        - cypress/videos/**/*.mp4
        - cypress/screenshots/**/*.png
        expire_in: 1 day